# Generated by Django 6.0.5 on 2026-05-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='university.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Semester Name'),
        ),
    ]
